//! Marked regions in the repository's markdown, filled from the registries.
//!
//! Everything Darkly registers already describes itself: a veil carries its own
//! display name and description, and the picker, `metadata.json` and the
//! documentation site all read that rather than restating it. Markdown checked
//! into this repository was the one consumer left restating it by hand, so a
//! table of veils in `README.md` drifted the moment a veil was added.
//!
//! A file opts a span of itself into being generated by bracketing it with HTML
//! comments, which render as nothing:
//!
//! ```markdown
//! <!-- darkly:catalog-table catalog=effects -->
//! …whatever the fragment writes…
//! <!-- /darkly:catalog-table -->
//! ```
//!
//! [`sync`] walks the tree, re-renders every region it finds and either writes
//! the result back or reports the drift. `cargo sync-docs` is the writer and
//! `tests/docs_md.rs` is the checker, so a stale region fails the ordinary test
//! suite and one command fixes it.
//!
//! Fragments are a modular registry: a new one is a new file in `fragments/`
//! exporting `pub fn register()`, and nothing here is edited to admit it.
//!
//! Needs no GPU, and reads no files: like [`crate::catalog`], every fragment
//! builds from the registries and from text embedded at compile time, which is
//! what lets the check run in the ordinary test suite rather than behind a
//! device.

pub mod fragments;

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Where preview stills for generated tables live, relative to the repository
/// root. Named once because two halves depend on it: the fragment that links to
/// a still, and `render_docs --stills`, which writes it.
pub const STILLS_DIR: &str = "docs/images/previews";

/// Directories the walk never descends into. `target` and `node_modules` are
/// build output; the rest are the prior-art checkouts `CONTRIBUTING.md` asks
/// for, tens of thousands of markdown files that are not ours to rewrite.
const SKIP_DIRS: &[&str] = &[
    "target",
    "node_modules",
    "krita",
    "krita-source",
    "gimp",
    "gegl",
];

// ---------------------------------------------------------------------------
// Fragments
// ---------------------------------------------------------------------------

/// One kind of generated region. `id` is what a marker names; `args` is the
/// complete set of keys it accepts, so an unrecognised key is caught by the
/// parser rather than ignored by the fragment.
pub struct FragmentRegistration {
    pub id: &'static str,
    pub args: &'static [&'static str],
    pub render: fn(&FragmentCtx) -> Result<String, FragmentError>,
}

/// Anything a fragment is allowed to know: the arguments its marker carried, and
/// where the file it is writing into sits.
///
/// Deliberately not the repository root. A fragment's output is a pure function
/// of the registries and these two fields, so `sync` in check mode answers the
/// same way whether or not the assets it links to have been rendered yet: a
/// row pointing at a missing image is a visible, testable failure, where a row
/// that silently omits itself is not.
pub struct FragmentCtx<'a> {
    args: BTreeMap<&'a str, &'a str>,
    /// The markdown file's directory, relative to the repository root. Empty for
    /// a file at the root.
    md_dir: &'a Path,
}

impl FragmentCtx<'_> {
    /// A declared argument's value.
    pub fn arg(&self, key: &str) -> Result<&str, FragmentError> {
        self.args
            .get(key)
            .copied()
            .ok_or_else(|| FragmentError(format!("`{key}` is required")))
    }

    /// A declared argument's value, or `None` when the region omits it. For an
    /// argument that narrows what a fragment renders rather than naming it.
    pub fn arg_opt(&self, key: &str) -> Option<&str> {
        self.args.get(key).copied()
    }

    /// A repository-relative path, rewritten to reach the same file from the
    /// markdown that links to it. Markdown resolves relative links against the
    /// file, not the root, so a fragment that emitted root-relative paths would
    /// work in `README.md` and nowhere else.
    pub fn link(&self, target: &str) -> String {
        let target = Path::new(target);
        let mut from = self.md_dir.components().peekable();
        let mut to = target.components().peekable();
        while from.peek().is_some() && from.peek() == to.peek() {
            from.next();
            to.next();
        }
        let mut parts: Vec<String> = from.map(|_| "..".to_string()).collect();
        parts.extend(to.map(|c| c.as_os_str().to_string_lossy().into_owned()));
        parts.join("/")
    }
}

/// Why a fragment could not render. Carries prose because there is nothing
/// generic to do with the failure but show it to whoever wrote the marker.
#[derive(Debug)]
pub struct FragmentError(pub String);

impl FragmentError {
    pub fn new(message: impl Into<String>) -> Self {
        FragmentError(message.into())
    }
}

fn fragment(id: &str) -> Option<FragmentRegistration> {
    fragments::registrations().into_iter().find(|f| f.id == id)
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// Where something went wrong, in the terms of the person who has to fix it: a
/// file, a line, and what the marker on that line did.
#[derive(Debug)]
pub struct SyncError {
    pub file: PathBuf,
    pub line: usize,
    pub kind: SyncErrorKind,
}

#[derive(Debug)]
pub enum SyncErrorKind {
    UnknownFragment(String),
    UnknownArg {
        id: String,
        key: String,
    },
    MalformedArg {
        id: String,
        token: String,
    },
    /// A region was opened and the file ended before it closed.
    Unterminated(String),
    /// A close marker naming a fragment other than the open one.
    MismatchedClose {
        open: String,
        close: String,
    },
    /// A close marker with no region open.
    StrayClose(String),
    Render {
        id: String,
        error: FragmentError,
    },
    Io(std::io::Error),
}

impl std::fmt::Display for SyncError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}:{}: ", self.file.display(), self.line)?;
        match &self.kind {
            SyncErrorKind::UnknownFragment(id) => {
                write!(f, "no fragment named `{id}`")
            }
            SyncErrorKind::UnknownArg { id, key } => {
                write!(f, "`{id}` accepts no argument `{key}`")
            }
            SyncErrorKind::MalformedArg { id, token } => {
                write!(f, "`{id}` got `{token}`, which is not `key=value`")
            }
            SyncErrorKind::Unterminated(id) => {
                write!(f, "`darkly:{id}` is never closed")
            }
            SyncErrorKind::MismatchedClose { open, close } => {
                write!(f, "`darkly:{open}` is closed by `/darkly:{close}`")
            }
            SyncErrorKind::StrayClose(id) => {
                write!(f, "`/darkly:{id}` closes a region that was never opened")
            }
            SyncErrorKind::Render { id, error } => {
                write!(f, "`{id}` could not render: {}", error.0)
            }
            SyncErrorKind::Io(e) => write!(f, "{e}"),
        }
    }
}

impl std::error::Error for SyncError {}

// ---------------------------------------------------------------------------
// Markers
// ---------------------------------------------------------------------------

/// How a target spells a comment, which is the only thing that varies between
/// the file types this system writes into.
///
/// Markdown and XML share `<!-- -->` exactly, which is why an AppStream
/// metainfo file needed no grammar of its own. A desktop entry has no such
/// syntax and uses `#`, which markdown must never be read with: `# Heading`
/// would parse as a comment body.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Syntax {
    /// `<!-- ... -->`, and `` ``` `` fences are honoured.
    Markdown,
    /// `<!-- ... -->`, with no fences.
    Xml,
    /// `# ...`, with no fences.
    Hash,
}

impl Syntax {
    /// The syntax a path is written in, or `None` for a file this system does
    /// not generate into.
    pub fn of(path: &Path) -> Option<Self> {
        match path.extension()?.to_str()? {
            "md" => Some(Syntax::Markdown),
            "xml" => Some(Syntax::Xml),
            "desktop" => Some(Syntax::Hash),
            _ => None,
        }
    }

    /// Whether fenced code blocks shield markers from being read as regions.
    fn fenced(self) -> bool {
        self == Syntax::Markdown
    }
}

/// The inside of a comment occupying a whole line, or `None` for any other
/// line. Indentation is tolerated so a region can sit inside a list item.
fn comment_body(line: &str, syntax: Syntax) -> Option<&str> {
    let t = line.trim();
    match syntax {
        Syntax::Markdown | Syntax::Xml => {
            t.strip_prefix("<!--")?.strip_suffix("-->").map(str::trim)
        }
        Syntax::Hash => t.strip_prefix('#').map(str::trim),
    }
}

/// The fragment a close marker names.
fn close_marker(line: &str, syntax: Syntax) -> Option<&str> {
    comment_body(line, syntax)?
        .strip_prefix("/darkly:")
        .map(str::trim)
}

/// The fragment an open marker names, with its arguments still unparsed.
fn open_marker(line: &str, syntax: Syntax) -> Option<(&str, &str)> {
    let body = comment_body(line, syntax)?.strip_prefix("darkly:")?;
    Some(match body.split_once(char::is_whitespace) {
        Some((id, rest)) => (id, rest.trim()),
        None => (body, ""),
    })
}

/// Whether the walk is inside a fenced code block, and which fence opened it.
///
/// A marker in a code block is an example, not a region. Documentation about
/// this system has to be able to show the syntax it is documenting:
/// `docs/generated-markdown.md` does, and without this it would rewrite its own
/// explanation into a table of effects.
#[derive(Default)]
struct Fence(Option<(char, usize)>);

impl Fence {
    /// Feed the next line and answer whether it is fenced. The fence lines
    /// themselves count as fenced, so neither can be mistaken for a marker.
    fn consume(&mut self, line: &str) -> bool {
        let text = line.trim_start();
        let opener = text.chars().next().filter(|c| *c == '`' || *c == '~');
        let run = opener.map_or(0, |c| text.chars().take_while(|x| *x == c).count());
        match self.0 {
            // A closing fence repeats the opener at least as many times and
            // carries no info string: ```rust closes nothing.
            Some((char, len)) => {
                if opener == Some(char) && run >= len && text[run..].trim().is_empty() {
                    self.0 = None;
                }
                true
            }
            None => {
                if run >= 3 {
                    self.0 = Some((opener.expect("a run implies its character"), run));
                    true
                } else {
                    false
                }
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Rendering one file
// ---------------------------------------------------------------------------

/// A file after its regions have been re-rendered.
pub struct Rendered {
    pub text: String,
    /// How many regions were found. Zero means the file only *mentions* the
    /// syntax (in a code fence, say) and nothing in it is generated.
    pub regions: usize,
}

/// Re-render every region in `text`. `rel` is the markdown file's path relative
/// to the repository root, used to place the file's directory in the context,
/// and to name the file in errors.
///
/// Everything outside a region is copied byte for byte. A file may hold any
/// number of regions, including several of the same fragment with different
/// arguments: one page listing two catalogs is a table each, not a conflict.
pub fn render_text(rel: &Path, text: &str) -> Result<Rendered, SyncError> {
    // A path this system does not generate into cannot hold a region, so it
    // renders to itself rather than erroring: `sync` never offers one, and a
    // caller that does gets its file back untouched.
    let Some(syntax) = Syntax::of(rel) else {
        return Ok(Rendered {
            text: text.to_string(),
            regions: 0,
        });
    };
    let md_dir = rel.parent().unwrap_or(Path::new(""));
    let err = |line: usize, kind: SyncErrorKind| SyncError {
        file: rel.to_path_buf(),
        line,
        kind,
    };

    let mut out = String::with_capacity(text.len());
    let mut open: Option<(String, usize)> = None;
    let mut regions = 0;
    // Only tracked outside a region: a region's body is about to be replaced, so
    // an unbalanced fence left in the old one says nothing about the file.
    let mut fence = Fence::default();

    for (i, line) in text.lines().enumerate() {
        let no = i + 1;

        if syntax.fenced() && open.is_none() && fence.consume(line) {
            out.push_str(line);
            out.push('\n');
            continue;
        }

        if let Some((id, arg_text)) = open_marker(line, syntax) {
            if let Some((outer, at)) = &open {
                // A marker inside a region is content the region owns, and the
                // region is about to be overwritten, so it cannot be one.
                return Err(err(*at, SyncErrorKind::Unterminated(outer.clone())));
            }
            let Some(reg) = fragment(id) else {
                return Err(err(no, SyncErrorKind::UnknownFragment(id.to_string())));
            };
            let mut args = BTreeMap::new();
            for token in arg_text.split_whitespace() {
                let Some((key, value)) = token.split_once('=') else {
                    return Err(err(
                        no,
                        SyncErrorKind::MalformedArg {
                            id: id.to_string(),
                            token: token.to_string(),
                        },
                    ));
                };
                if !reg.args.contains(&key) {
                    return Err(err(
                        no,
                        SyncErrorKind::UnknownArg {
                            id: id.to_string(),
                            key: key.to_string(),
                        },
                    ));
                }
                args.insert(key, value);
            }
            let body = (reg.render)(&FragmentCtx { args, md_dir }).map_err(|error| {
                err(
                    no,
                    SyncErrorKind::Render {
                        id: id.to_string(),
                        error,
                    },
                )
            })?;
            out.push_str(line);
            out.push('\n');
            out.push_str(body.trim_end_matches('\n'));
            out.push('\n');
            open = Some((id.to_string(), no));
            regions += 1;
            continue;
        }

        if let Some(id) = close_marker(line, syntax) {
            match open.take() {
                None => return Err(err(no, SyncErrorKind::StrayClose(id.to_string()))),
                Some((opened, _)) if opened != id => {
                    return Err(err(
                        no,
                        SyncErrorKind::MismatchedClose {
                            open: opened,
                            close: id.to_string(),
                        },
                    ))
                }
                Some(_) => {}
            }
            out.push_str(line);
            out.push('\n');
            continue;
        }

        // Inside a region the old body is dropped; the new one is already out.
        if open.is_none() {
            out.push_str(line);
            out.push('\n');
        }
    }

    if let Some((id, at)) = open {
        return Err(err(at, SyncErrorKind::Unterminated(id)));
    }

    // `lines()` discards the distinction between a file ending in a newline and
    // one that does not, and rewriting that is not this tool's business.
    if !text.ends_with('\n') {
        out.pop();
    }
    Ok(Rendered { text: out, regions })
}

// ---------------------------------------------------------------------------
// Walking the tree
// ---------------------------------------------------------------------------

/// Every file under `root` this system can generate into, relative to it, in a
/// stable order. See [`Syntax::of`] for which those are.
pub fn generated_files(root: &Path) -> Result<Vec<PathBuf>, std::io::Error> {
    let mut found = Vec::new();
    walk(root, Path::new(""), &mut found)?;
    found.sort();
    Ok(found)
}

fn walk(root: &Path, rel: &Path, found: &mut Vec<PathBuf>) -> Result<(), std::io::Error> {
    for entry in std::fs::read_dir(root.join(rel))? {
        let entry = entry?;
        let name = entry.file_name();
        let name = name.to_string_lossy();
        let path = rel.join(name.as_ref());
        // Symlinks are never followed. `AGENTS.md` and `CLAUDE.md` are links to
        // `CONTRIBUTING.md`, and rewriting one file three times under three
        // names is at best noise in the report; a link pointing out of the tree
        // would be worse. A link's target is walked on its own if it is in the
        // tree, which is where it belongs.
        if entry.file_type()?.is_symlink() {
            continue;
        }
        if entry.file_type()?.is_dir() {
            // Hidden directories are tooling (`.git`, `.github`, `.cargo`);
            // nothing in them is documentation a reader browses.
            if name.starts_with('.') || SKIP_DIRS.contains(&name.as_ref()) {
                continue;
            }
            walk(root, &path, found)?;
        } else if Syntax::of(&path).is_some() {
            found.push(path);
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// The whole tree
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Mode {
    /// Rewrite files whose regions are out of date.
    Write,
    /// Report them and change nothing.
    Check,
}

/// What `sync` found, in repository-relative paths.
#[derive(Debug, Default)]
pub struct Report {
    /// Files that were rewritten, or in [`Mode::Check`] would have been.
    pub changed: Vec<PathBuf>,
    /// Files holding at least one region, what the run actually covered.
    pub generated: Vec<PathBuf>,
}

/// Re-render every region in every markdown file under `root`.
pub fn sync(root: &Path, mode: Mode) -> Result<Report, SyncError> {
    let io = |e: std::io::Error, file: &Path| SyncError {
        file: file.to_path_buf(),
        line: 0,
        kind: SyncErrorKind::Io(e),
    };

    let mut report = Report::default();
    for rel in generated_files(root).map_err(|e| io(e, root))? {
        let path = root.join(&rel);
        let text = std::fs::read_to_string(&path).map_err(|e| io(e, &rel))?;
        if !text.contains("darkly:") {
            continue;
        }
        let rendered = render_text(&rel, &text)?;
        if rendered.regions == 0 {
            continue;
        }
        report.generated.push(rel.clone());
        if rendered.text == text {
            continue;
        }
        report.changed.push(rel.clone());
        if mode == Mode::Write {
            std::fs::write(&path, rendered.text).map_err(|e| io(e, &rel))?;
        }
    }
    Ok(report)
}

/// The repository root, derived from this crate's location.
///
/// The binary and the tests both need it and neither should guess: a
/// `current_dir` answer depends on where the caller stood, and `cargo test` and
/// a git hook do not stand in the same place.
pub fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap_or_else(|_| PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../.."))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn render(text: &str) -> Result<String, SyncError> {
        render_text(Path::new("README.md"), text).map(|r| r.text)
    }

    fn regions(text: &str) -> usize {
        render_text(Path::new("README.md"), text)
            .expect("the markdown parses")
            .regions
    }

    /// The one fragment shipped today, rendered into the smallest file that can
    /// hold it. Used by the tests that care about the machinery rather than the
    /// table.
    const OPEN: &str = "<!-- darkly:catalog-table catalog=effects -->";
    const CLOSE: &str = "<!-- /darkly:catalog-table -->";

    #[test]
    fn text_outside_a_region_survives_byte_for_byte() {
        let text = format!("# Title\n\nprose\n\n{OPEN}\nstale\n{CLOSE}\n\nmore prose\n");
        let out = render(&text).unwrap();
        assert!(out.starts_with("# Title\n\nprose\n\n"));
        assert!(out.ends_with("\n\nmore prose\n"));
        assert!(!out.contains("stale"));
    }

    #[test]
    fn a_file_with_no_markers_is_unchanged() {
        let text = "# Title\n\njust prose.\n";
        assert_eq!(render(text).unwrap(), text);
    }

    #[test]
    fn rendering_is_idempotent() {
        let text = format!("intro\n\n{OPEN}\n{CLOSE}\n");
        let once = render(&text).unwrap();
        assert_eq!(render(&once).unwrap(), once);
    }

    #[test]
    fn a_missing_trailing_newline_is_not_invented() {
        let text = format!("{OPEN}\n{CLOSE}");
        assert!(!render(&text).unwrap().ends_with('\n'));
    }

    /// A markdown heading is not a marker.
    ///
    /// The desktop-entry syntax reads `#` as a comment introducer. Markdown
    /// must never be parsed that way: every `## Rules` in this repository's own
    /// documentation would become a comment body, and one of them starting with
    /// `darkly:` would open a region nobody wrote.
    #[test]
    fn a_markdown_heading_is_not_a_marker() {
        assert_eq!(comment_body("# Versioning", Syntax::Markdown), None);
        assert_eq!(comment_body("# darkly:app-summary", Syntax::Markdown), None);
        assert_eq!(open_marker("# darkly:app-summary", Syntax::Markdown), None);
    }

    /// The desktop-entry syntax reads its own comments, and only its own.
    #[test]
    fn hash_syntax_reads_hash_comments() {
        assert_eq!(
            open_marker("# darkly:app-desktop-entry", Syntax::Hash),
            Some(("app-desktop-entry", ""))
        );
        assert_eq!(
            close_marker("# /darkly:app-desktop-entry", Syntax::Hash),
            Some("app-desktop-entry")
        );
        // An ordinary comment is not a marker.
        assert_eq!(open_marker("# just a note", Syntax::Hash), None);
    }

    /// XML needs no grammar of its own: its comments are markdown's exactly.
    #[test]
    fn xml_shares_the_html_comment_grammar() {
        assert_eq!(
            open_marker("<!-- darkly:app-summary -->", Syntax::Xml),
            Some(("app-summary", ""))
        );
        assert_eq!(
            close_marker("<!-- /darkly:app-summary -->", Syntax::Xml),
            Some("app-summary")
        );
    }

    /// Which files the system will generate into, and which it refuses.
    #[test]
    fn syntax_is_chosen_by_extension() {
        use std::path::Path;
        assert_eq!(Syntax::of(Path::new("README.md")), Some(Syntax::Markdown));
        assert_eq!(Syntax::of(Path::new("a.metainfo.xml")), Some(Syntax::Xml));
        assert_eq!(Syntax::of(Path::new("a.desktop")), Some(Syntax::Hash));
        // Not a target: JSON has no comment syntax to hide a marker in, which
        // is why packaging/app.json is written whole instead.
        assert_eq!(Syntax::of(Path::new("app.json")), None);
        assert_eq!(Syntax::of(Path::new("main.rs")), None);
    }

    #[test]
    fn two_regions_of_one_fragment_are_allowed() {
        let text = format!("{OPEN}\n{CLOSE}\n\n{OPEN}\n{CLOSE}\n");
        let out = render(&text).unwrap();
        assert_eq!(out.matches("| Name |").count(), 2);
        assert_eq!(regions(&text), 2);
    }

    /// A marker in a code block is documentation *about* the syntax, and
    /// `docs/generated-markdown.md` is full of it. Rewriting an explanation
    /// into an effects table was this tool's first act on the repository,
    /// before fences were understood.
    #[test]
    fn markers_inside_a_code_fence_are_examples() {
        let text = format!("Like so:\n\n```markdown\n{OPEN}\n…\n{CLOSE}\n```\n\nSee?\n");
        assert_eq!(render(&text).unwrap(), text);
        assert_eq!(regions(&text), 0);
    }

    /// The info string is part of the opening fence, not a second fence, and a
    /// tilde fence is a fence: a file that mixes them must still come out
    /// unchanged.
    #[test]
    fn fences_close_only_on_their_own_terms() {
        let text = format!("```rust\nlet x = 1;\n```\n\n~~~\n{OPEN}\n~~~\n\n{OPEN}\n{CLOSE}\n");
        assert_eq!(regions(&text), 1, "only the unfenced marker is a region");

        // A longer run closes a shorter fence; a shorter one does not close a
        // longer one, so the marker between them stays fenced.
        let text = format!("````\n```\n{OPEN}\n````\n");
        assert_eq!(regions(&text), 0);
    }

    /// A fence *inside* a region is content that is about to be replaced, so it
    /// cannot leave the parser thinking the rest of the file is code.
    #[test]
    fn a_fence_in_a_stale_region_body_does_not_escape_it() {
        let text = format!("{OPEN}\n```\nstale\n{CLOSE}\n\n{OPEN}\n{CLOSE}\n");
        assert_eq!(regions(&text), 2);
    }

    #[test]
    fn an_unknown_fragment_is_an_error() {
        let err = render("<!-- darkly:nonsense -->\n<!-- /darkly:nonsense -->\n").unwrap_err();
        assert!(
            matches!(err.kind, SyncErrorKind::UnknownFragment(_)),
            "{err}"
        );
    }

    #[test]
    fn an_unknown_argument_is_an_error() {
        let text = "<!-- darkly:catalog-table catalog=effects sort=name -->\n<!-- /darkly:catalog-table -->\n";
        let err = render(text).unwrap_err();
        assert!(
            matches!(err.kind, SyncErrorKind::UnknownArg { .. }),
            "{err}"
        );
    }

    #[test]
    fn a_bare_argument_token_is_an_error() {
        let text = "<!-- darkly:catalog-table veils -->\n<!-- /darkly:catalog-table -->\n";
        let err = render(text).unwrap_err();
        assert!(
            matches!(err.kind, SyncErrorKind::MalformedArg { .. }),
            "{err}"
        );
    }

    #[test]
    fn an_unterminated_region_is_an_error() {
        let err = render(&format!("{OPEN}\nbody\n")).unwrap_err();
        assert!(matches!(err.kind, SyncErrorKind::Unterminated(_)), "{err}");
    }

    #[test]
    fn a_close_naming_another_fragment_is_an_error() {
        let err = render(&format!("{OPEN}\n<!-- /darkly:something-else -->\n")).unwrap_err();
        assert!(
            matches!(err.kind, SyncErrorKind::MismatchedClose { .. }),
            "{err}"
        );
    }

    #[test]
    fn a_close_with_nothing_open_is_an_error() {
        let err = render(&format!("prose\n{CLOSE}\n")).unwrap_err();
        assert!(matches!(err.kind, SyncErrorKind::StrayClose(_)), "{err}");
    }

    #[test]
    fn a_fragment_that_cannot_render_names_itself() {
        let text = "<!-- darkly:catalog-table catalog=nope -->\n<!-- /darkly:catalog-table -->\n";
        let err = render(text).unwrap_err();
        assert!(matches!(err.kind, SyncErrorKind::Render { .. }), "{err}");
    }

    /// Links resolve against the file that carries them, not the repository
    /// root, the whole reason a fragment is handed a directory.
    #[test]
    fn links_are_relative_to_the_markdown_file() {
        let at_root = FragmentCtx {
            args: BTreeMap::new(),
            md_dir: Path::new(""),
        };
        assert_eq!(at_root.link("docs/images/a.jpg"), "docs/images/a.jpg");

        let nested = FragmentCtx {
            args: BTreeMap::new(),
            md_dir: Path::new("docs/manual"),
        };
        assert_eq!(nested.link("docs/images/a.jpg"), "../images/a.jpg");

        let sibling = FragmentCtx {
            args: BTreeMap::new(),
            md_dir: Path::new("crates/darkly"),
        };
        assert_eq!(sibling.link("docs/images/a.jpg"), "../../docs/images/a.jpg");
    }

    /// The walk must not wander into the prior-art checkouts: `krita/` alone is
    /// thousands of markdown files, and rewriting any of them would be wrong.
    #[test]
    fn the_walk_skips_vendored_and_hidden_directories() {
        let files = generated_files(&repo_root()).unwrap();
        assert!(files.iter().any(|p| p == Path::new("README.md")));
        for f in &files {
            let first = f.components().next().unwrap().as_os_str().to_string_lossy();
            assert!(
                !SKIP_DIRS.contains(&first.as_ref()) && !first.starts_with('.'),
                "walk descended into `{}`",
                f.display()
            );
        }
    }

    /// `AGENTS.md` and `CLAUDE.md` are symlinks to `CONTRIBUTING.md`. One file,
    /// one entry; otherwise a report names the same content three times and a
    /// link out of the tree would be followed out of it.
    #[test]
    fn the_walk_reaches_a_linked_file_once_under_its_real_name() {
        let files = generated_files(&repo_root()).unwrap();
        assert!(files.iter().any(|p| p == Path::new("CONTRIBUTING.md")));
        for link in ["AGENTS.md", "CLAUDE.md"] {
            assert!(
                !files.iter().any(|p| p == Path::new(link)),
                "`{link}` was walked as well as its target"
            );
        }
    }
}
