//! Built-in brushes shipped with the application.
//!
//! Each brush is a YAML file under `crates/darkly/brushes/` that
//! describes its node graph in the [`PortableBrush`] format. The
//! build script (`crates/darkly/build.rs`) embeds every `.yaml` in
//! that directory at compile time: adding a new brush is "drop a
//! file, no code changes." See the modularity rules in CONTRIBUTING.md.

use std::sync::OnceLock;

use crate::brush::library::BrushInfo;
use crate::brush::metadata::Brush;
use crate::brush::portable::PortableBrush;
use crate::catalog::{Catalog, CatalogEntry};
use crate::gpu::preview::PreviewAnim;

// `BUILTIN_BRUSHES_YAML: &[(filename, yaml_source)]`, generated by
// `crates/darkly/build.rs` from `crates/darkly/brushes/*.yaml`.
include!(concat!(env!("OUT_DIR"), "/builtin_brushes_gen.rs"));

/// Every built-in brush, paired with its YAML file stem.
///
/// Parse and import failures panic: a built-in brush failing to load
/// is a build-time bug in the shipped YAML, not a runtime error the
/// caller can recover from.
fn parsed() -> Vec<(&'static str, Brush)> {
    let registry = crate::brush::registry();
    BUILTIN_BRUSHES_YAML
        .iter()
        .map(|(filename, yaml)| {
            let stem = filename
                .strip_suffix(".yaml")
                .expect("build.rs names every embedded brush `<stem>.yaml`");
            let portable: PortableBrush = serde_yaml_ng::from_str(yaml)
                .unwrap_or_else(|e| panic!("invalid built-in brush '{filename}': {e}"));
            let brush = portable
                .into_brush(registry, stem)
                .unwrap_or_else(|e| panic!("invalid built-in brush '{filename}': {e}"))
                .into_shipped();
            (stem, brush)
        })
        .collect()
}

/// All built-in brushes, parsed from their YAML sources.
pub fn all() -> Vec<Brush> {
    parsed().into_iter().map(|(_, brush)| brush).collect()
}

/// The shipped brushes' listable metadata, parsed once for the process,
/// each paired with its YAML file stem.
///
/// Every brush is embedded at compile time, so the set is fixed and a
/// process-lifetime cache is the data's real lifetime rather than an
/// approximation of it. Holding the parse here is what lets a
/// [`CatalogEntry`]'s `&'static str` fields borrow strings that arrived as
/// owned YAML values, without leaking, and without widening the catalog
/// types to `Cow` for the one registry that is not wholly static.
///
/// The row is [`BrushInfo`] itself rather than a parallel doc struct, so the
/// picker and the documentation read the identical summary by construction.
/// The file stem is the only thing `BrushInfo` does not carry, so it rides
/// alongside.
pub fn docs() -> &'static [(&'static str, BrushInfo)] {
    static DOCS: OnceLock<Vec<(&'static str, BrushInfo)>> = OnceLock::new();
    DOCS.get_or_init(|| {
        parsed()
            .into_iter()
            .map(|(stem, brush)| (stem, BrushInfo::from(&brush)))
            .collect()
    })
    .as_slice()
}

/// Id of the catalog the shipped brushes project into.
pub const CATALOG_ID: &str = "brushes";

/// How a brush's preview plays back: it does not. A brush's preview is one
/// finished stroke, and the finished stroke is the answer to "what does this
/// brush look like"; watching the line appear adds nothing the way watching a
/// veil's parameter sweep does, and it would cost forty-eight full re-renders
/// per brush for it. Krita's live preview repaints the whole stroke on every
/// change and never animates it either.
///
/// Declared on the catalog rather than on any single brush for the same reason
/// blend modes declare theirs there: the motion (or the lack of it) is the
/// same for every entry, so a fifteenth brush is still one YAML file and
/// inherits this for free. A brush that ever wants motion is a `preview` field
/// on its metadata and a fallback to this in [`preview`], local to this file.
pub static PREVIEW: PreviewAnim = PreviewAnim::STILL;

/// How long a brush's preview runs. Every shipped brush inherits [`PREVIEW`];
/// an unknown stem gets `None`.
///
/// The single authority on whether a brush is previewable: [`catalog`] derives
/// the flag by asking this rather than asserting it, so declaring an animation
/// stays the one way to say an entry has a preview.
pub fn preview(type_id: &str) -> Option<PreviewAnim> {
    docs()
        .iter()
        .any(|(stem, _)| *stem == type_id)
        .then_some(PREVIEW)
}

/// The brush catalog: every shipped built-in, sorted by `type_id`.
///
/// `type_id` is the YAML file stem (`rough_watercolor`), not the brush's
/// name: it is snake_case like every other catalog's type ids, and
/// `docs_render` uses `catalog.id / entry.type_id` as a real directory path,
/// which `"Rough Watercolor"` would not survive. `displayName` carries the
/// name, and the name is what a consumer keys by against the running app:
/// [`BrushLibrary`](crate::brush::library::BrushLibrary) stores brushes under
/// it.
///
/// Alone among the catalogs this one parses on its first call, so it inherits
/// [`parsed`]'s panic on malformed shipped YAML, which the whole of
/// `catalogs()` then carries. That is the same bug `all()` already panics on
/// at engine init, surfacing one call earlier.
pub fn catalog() -> Catalog {
    Catalog::new(
        CATALOG_ID,
        "Brushes",
        docs()
            .iter()
            .map(|(stem, info)| {
                let entry = CatalogEntry::new(stem, info.name.as_str())
                    .with_description(info.description.as_str())
                    // Grouping is derived, not stored: membership lives on
                    // the pack and a brush may be in several, so this is one
                    // stored fact projected into the export rather than two to
                    // keep in agreement.
                    .with_category(
                        crate::brush::packs::pack_of(stem)
                            .map(|p| p.name.as_str())
                            .unwrap_or(""),
                    )
                    // Brushes carry no `preview` field of their own (the recipe
                    // lives on the catalog), so previewability is the same
                    // question put to the same authority.
                    .with_supports_preview(preview(stem).is_some());
                match info.icon {
                    Some(icon) => entry.with_icon(icon),
                    None => entry,
                }
            })
            .collect(),
    )
    .with_description(
        "The brushes Darkly ships with, grouped by the medium they imitate. \
         This is the shipped set; a running session's library also holds \
         whatever the painter has loaded.",
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_brushes_compile() {
        for brush in all() {
            let result = crate::brush::compile_graph(&brush.metadata.graph);
            assert!(
                result.is_ok(),
                "brush '{}' failed to compile: {:?}",
                brush.metadata.name,
                result.err(),
            );
        }
    }

    /// Node ids are interpolated directly into WGSL symbols (`n{id}_{port}`,
    /// `{base}_{id}`), so every id in every built-in brush must be a valid
    /// WGSL identifier fragment: `[A-Za-z_][A-Za-z0-9_]*`. Kind-derived ids
    /// (`noise`, `noise_2`, `brush_settings`) satisfy this by construction;
    /// this guards the invariant against a future node kind whose `type_id`
    /// carries an illegal character.
    #[test]
    fn builtin_brush_node_ids_are_valid_wgsl_identifiers() {
        fn valid(id: &str) -> bool {
            let mut chars = id.chars();
            matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_')
                && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
        }
        for brush in all() {
            for id in brush.metadata.graph.nodes().keys() {
                assert!(
                    valid(id.as_str()),
                    "brush '{}' node id '{}' is not a valid WGSL identifier",
                    brush.metadata.name,
                    id,
                );
            }
        }
    }

    #[test]
    fn builtin_brushes_round_trip_through_a_pack() {
        // Every shipped brush must survive the archive it would be shared in,
        // which is a pack, even when it holds one brush.
        use crate::brush::pack::BrushPack;
        use crate::brush::pack_file::PackFile;

        for brush in all() {
            let (id, name) = (brush.id().to_string(), brush.name().to_string());
            let mut pack = BrushPack::new(
                "p",
                "Pack",
                "mdi:brush",
                crate::brush::pack::PackPalette::new("#2f7fe0", "#2fd0c0", "#0c1a26"),
            );
            pack.members = vec![id.clone()];

            let bytes = PackFile::new(&pack, vec![brush.metadata.clone()])
                .to_bytes()
                .unwrap();
            let loaded = PackFile::from_bytes(&bytes).unwrap();

            assert_eq!(loaded.brushes.len(), 1, "'{id}' round-trips as one brush");
            assert_eq!(loaded.brushes[0].id, id);
            assert_eq!(loaded.brushes[0].name, name);
        }
    }

    #[test]
    fn builtin_brushes_no_overlapping_nodes() {
        for brush in all() {
            let layout = brush.metadata.graph.auto_layout();
            let positions: Vec<[i32; 2]> = layout
                .values()
                .map(|p| [p[0] as i32, p[1] as i32])
                .collect();
            for (i, a) in positions.iter().enumerate() {
                for b in &positions[i + 1..] {
                    assert_ne!(
                        a, b,
                        "brush '{}' has overlapping nodes at {:?}",
                        brush.metadata.name, a,
                    );
                }
            }
        }
    }

    /// Content-dependent brushes (their graphs sample existing canvas
    /// pixels, so a still dab over the flat preview bake renders blank)
    /// must carry a preview fallback icon on their `BrushInfo`;
    /// content-free brushes must not. Rough Watercolor is the
    /// discriminator that proves the trigger is `preview_staging` and not
    /// `supports_erase`: its terminal sets `supports_erase = false` yet
    /// its preview bake is meaningful, so it gets no icon.
    #[test]
    fn content_dependent_brushes_get_preview_icons() {
        use crate::brush::library::BrushInfo;

        let expected = [
            ("Clone", Some("fa6-solid:clone")),
            ("Blur", Some("mdi:blur")),
            ("Smudge", Some("mdi:gesture-swipe")),
            ("Liquify", Some("tabler:ripple")),
            ("Ink Pen", None),
            ("Airbrush", None),
            ("Rough Watercolor", None),
        ];
        let brushes = all();
        for (name, icon) in expected {
            let brush = brushes
                .iter()
                .find(|b| b.metadata.name == name)
                .unwrap_or_else(|| panic!("built-in brush '{name}' must exist"));
            assert_eq!(
                BrushInfo::from(brush).icon,
                icon,
                "brush '{name}' preview fallback icon"
            );
        }
    }

    /// The catalog projects exactly the shipped set, keyed by file stem.
    /// Catches a brush file that stops being projected; that the
    /// descriptions are non-empty is
    /// `catalog::tests::every_catalog_entry_is_documented`'s job, for every
    /// catalog at once.
    #[test]
    fn the_brush_catalog_covers_every_shipped_brush() {
        let projected: Vec<&str> = catalog().entries.iter().map(|e| e.type_id).collect();
        let stems: Vec<&str> = BUILTIN_BRUSHES_YAML
            .iter()
            .map(|(filename, _)| filename.strip_suffix(".yaml").unwrap())
            .collect();
        assert_eq!(projected, stems, "brushes is not the shipped set");
    }

    #[test]
    fn builtin_brushes_unique_names() {
        let brushes = all();
        let mut names: Vec<_> = brushes.iter().map(|b| b.metadata.name.clone()).collect();
        names.sort();
        names.dedup();
        assert_eq!(names.len(), brushes.len(), "duplicate brush names");
    }

    /// Liquify needs much tighter spacing than the paint default: its
    /// per-dab displacement is ~25% of radius, so spacing must be well
    /// below that for warps to compose smoothly. Don't let this drift back
    /// to the default 10%.
    #[test]
    fn liquify_brush_has_tight_spacing() {
        let brush = all()
            .into_iter()
            .find(|b| b.metadata.name == "Liquify")
            .expect("Liquify built-in must exist");
        let spacing = crate::brush::nodes::brush_settings::read_scalar_input(
            &brush.metadata.graph,
            "spacing",
        )
        .expect("liquify brush_settings has a spacing port");
        assert!(
            spacing <= 0.05,
            "liquify spacing default is {spacing}, expected <= 5% for smooth warps",
        );
    }

    /// The Highlighter's identity is the wash end of the accumulation dial:
    /// one flat tint, and a stroke can never darken itself by crossing its
    /// own path. It also ships translucent, like the felt tip it names. Pin
    /// both: any `buildup` lets its own dabs stack, and full `opacity` makes
    /// it a marker, not a highlighter.
    #[test]
    fn highlighter_is_pure_wash_and_translucent() {
        let brush = all()
            .into_iter()
            .find(|b| b.metadata.name == "Highlighter")
            .expect("Highlighter built-in must exist");
        let paint = brush
            .metadata
            .graph
            .nodes()
            .values()
            .find(|n| n.type_id == crate::brush::nodes::paint::TYPE_ID)
            .expect("Highlighter has a paint terminal");
        let input = |name: &str| {
            paint
                .ports
                .iter()
                .find(|p| p.name == name && p.dir == crate::nodegraph::PortDir::Input)
                .map(|p| p.value.as_f32())
        };
        assert_eq!(
            input("buildup"),
            Some(0.0),
            "Highlighter must sit at the wash end of the accumulation dial",
        );
        assert!(
            input("opacity").is_some_and(|o| o < 1.0),
            "Highlighter ships translucent, not fully opaque",
        );
    }
}
