// @generated by build.rs: do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::brush::BrushNodeRegistration`.

pub mod add;
pub mod blur;
pub mod brush_settings;
pub mod circle;
pub mod clone_source;
pub mod curve;
pub mod divide;
pub mod image;
pub mod levels;
pub mod liquify;
pub mod multiply;
pub mod noise;
pub mod paint;
pub mod paint_color;
pub mod pattern;
pub mod pen_input;
pub mod polygon;
pub mod random;
pub mod smudge;
pub mod split_color;
pub mod stamp;
pub mod subtract;
pub mod switch;
pub mod watercolor;

use crate::brush::BrushNodeRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<BrushNodeRegistration> {
    vec![
        add::register(),
        blur::register(),
        brush_settings::register(),
        circle::register(),
        clone_source::register(),
        curve::register(),
        divide::register(),
        image::register(),
        levels::register(),
        liquify::register(),
        multiply::register(),
        noise::register(),
        paint::register(),
        paint_color::register(),
        pattern::register(),
        pen_input::register(),
        polygon::register(),
        random::register(),
        smudge::register(),
        split_color::register(),
        stamp::register(),
        subtract::register(),
        switch::register(),
        watercolor::register(),
    ]
}
